import {
  Car,
  Menu,
  Home,
  Search,
  Phone,
  FileText,
  LogIn,
  LogOut,
  Plus,
  Edit,
  Trash,
  Settings,
  User,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  AlertTriangle,
  Filter,
  Sparkles,
  Clock,
  Zap,
  Fuel,
  Truck,
  Leaf,
  DollarSign,
  Shield,
  Calendar,
  RefreshCw,
  Check,
  X
} from 'lucide-react';

export const Icons = {
  car: Car,
  menu: Menu,
  home: Home,
  search: Search,
  contact: Phone,
  about: FileText,
  login: LogIn,
  logout: LogOut,
  add: Plus,
  edit: Edit,
  delete: Trash,
  settings: Settings,
  user: User,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  warning: AlertTriangle,
  filter: Filter,
  sparkles: Sparkles,
  clock: Clock,
  zap: Zap,
  fuel: Fuel,
  truck: Truck,
  leaf: Leaf,
  dollar: DollarSign,
  shield: Shield,
  calendar: Calendar,
  refresh: RefreshCw,
  check: Check,
  x: X
} as const;